# Нейронные сети

## Домашнее задание 2. Numpy и функции

# Light

### Задача 1

1. Перейдите по ссылке https://drive.google.com/open?id=1ngnrhmoMInequrA6JyAe90lEPhcbi0iH


2. Сохраните файл на вашем google drive (скачивать на пк не нужно)


3. Присоедините google drive к ноутбуку


4. Откройте файл **train_vector_1.csv** с помощью функции **np.loadtxt**, указав полный путь до файла на google drive

In [ ]:
from google.colab import drive
drive.mount ('/content/drive')


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
import numpy as np
my_data=np.loadtxt('/content/drive/My Drive/Bases/train_vector_1.csv')
print(my_data)

[3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
 3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
 3.5 3.6 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
 2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8
 2.5 2.8 2.9 3.  2.8 3.  2.9 2.6 2.4 2.4 2.7 2.7 3.  3.4 3.1 2.3 3.  2.5
 2.6 3.  2.6 2.3 2.7 3.  2.9 2.9 2.5 2.8 3.3 2.7 3.  2.9 3.  3.  2.5 2.9
 2.5 3.6 3.2 2.7 3.  2.5 2.8 3.2 3.  3.8 2.6 2.2 3.2 2.8 2.8 2.7 3.3 3.2
 2.8 3.  2.8 3.  2.8 3.8 2.8 2.8 2.6 3.  3.4 3.1 3.  3.1 3.1 3.1 2.7 3.2
 3.3 3.  2.5 3.  3.4 3. ]


### Задача 2

1. Перейдите по ссылке https://drive.google.com/open?id=1ngnrhmoMInequrA6JyAe90lEPhcbi0iH

2. Сохраните файл на пк (в этой задаче пользоваться google drive не нужно)

3. Нажмите слева на значок папки и перетащите файл с пк в появившееся поле

4. Откройте файл **train_vector_1.csv** с помощью функции **np.loadtxt**, указав полный или относительный путь до файла

In [ ]:
my_data=np.loadtxt('/content/train_vector_1.csv')
print(my_data)

[3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
 3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
 3.5 3.6 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
 2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8
 2.5 2.8 2.9 3.  2.8 3.  2.9 2.6 2.4 2.4 2.7 2.7 3.  3.4 3.1 2.3 3.  2.5
 2.6 3.  2.6 2.3 2.7 3.  2.9 2.9 2.5 2.8 3.3 2.7 3.  2.9 3.  3.  2.5 2.9
 2.5 3.6 3.2 2.7 3.  2.5 2.8 3.2 3.  3.8 2.6 2.2 3.2 2.8 2.8 2.7 3.3 3.2
 2.8 3.  2.8 3.  2.8 3.8 2.8 2.8 2.6 3.  3.4 3.1 3.  3.1 3.1 3.1 2.7 3.2
 3.3 3.  2.5 3.  3.4 3. ]


### Задача 3

Работайте с массивом, полученным в предыдущих задачах.

* Напишите код, который считает среднее значение всех элементов массива (без использования встроенных функций np.mean(), np.sum() и т.д.). Для решения задачи воспользуйтесь циклом.
С помощью команды %%timeit отобразите время выполнения написанного кода.


* В новой ячейке посчитайте среднее значение всех элементов списка. В этот раз используйте функцию np.mean(). Командой %%timeit отобразите время выполнения и этой ячейки.

In [ ]:
%%timeit 
sum=0
for i in my_data:
  sum=sum+i
avarage=sum/my_data.size
#print(avarage)

10000 loops, best of 3: 31.8 µs per loop


In [ ]:
%%timeit
my_data.mean()

The slowest run took 75.60 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.94 µs per loop


### Задача 4

1. Перейдите по ссылке на файл **iris.csv** (ссылка в getcourse)

2. Сохраните файл на пк (в этой задаче пользоваться google drive не нужно)

3. Загрузите файл в ноутбук с помощью **files.upload**

4. Откройте файл **iris.csv** с помощью функции **np.loadtxt**, указав полный или относительный путь до файла

In [ ]:
from google.colab import files
files.upload()

Saving iris.csv to iris.csv


{'iris.csv': b',sepal.length,sepal.width,petal.length,petal.width\n0,5.1,3.5,1.4,0.2\n1,4.9,3.0,1.4,0.2\n2,4.7,3.2,1.3,0.2\n3,4.6,3.1,1.5,0.2\n4,5.0,3.6,1.4,0.2\n5,5.4,3.9,1.7,0.4\n6,4.6,3.4,1.4,0.3\n7,5.0,3.4,1.5,0.2\n8,4.4,2.9,1.4,0.2\n9,4.9,3.1,1.5,0.1\n10,5.4,3.7,1.5,0.2\n11,4.8,3.4,1.6,0.2\n12,4.8,3.0,1.4,0.1\n13,4.3,3.0,1.1,0.1\n14,5.8,4.0,1.2,0.2\n15,5.7,4.4,1.5,0.4\n16,5.4,3.9,1.3,0.4\n17,5.1,3.5,1.4,0.3\n18,5.7,3.8,1.7,0.3\n19,5.1,3.8,1.5,0.3\n20,5.4,3.4,1.7,0.2\n21,5.1,3.7,1.5,0.4\n22,4.6,3.6,1.0,0.2\n23,5.1,3.3,1.7,0.5\n24,4.8,3.4,1.9,0.2\n25,5.0,3.0,1.6,0.2\n26,5.0,3.4,1.6,0.4\n27,5.2,3.5,1.5,0.2\n28,5.2,3.4,1.4,0.2\n29,4.7,3.2,1.6,0.2\n30,4.8,3.1,1.6,0.2\n31,5.4,3.4,1.5,0.4\n32,5.2,4.1,1.5,0.1\n33,5.5,4.2,1.4,0.2\n34,4.9,3.1,1.5,0.2\n35,5.0,3.2,1.2,0.2\n36,5.5,3.5,1.3,0.2\n37,4.9,3.6,1.4,0.1\n38,4.4,3.0,1.3,0.2\n39,5.1,3.4,1.5,0.2\n40,5.0,3.5,1.3,0.3\n41,4.5,2.3,1.3,0.3\n42,4.4,3.2,1.3,0.2\n43,5.0,3.5,1.6,0.6\n44,5.1,3.8,1.9,0.4\n45,4.8,3.0,1.4,0.3\n46,5.1,3.8,1.6,0.2\n47,

In [ ]:
np.loadtxt('/content/iris.csv', delimiter=',',skiprows=1)

array([[0.00e+00, 5.10e+00, 3.50e+00, 1.40e+00, 2.00e-01],
       [1.00e+00, 4.90e+00, 3.00e+00, 1.40e+00, 2.00e-01],
       [2.00e+00, 4.70e+00, 3.20e+00, 1.30e+00, 2.00e-01],
       [3.00e+00, 4.60e+00, 3.10e+00, 1.50e+00, 2.00e-01],
       [4.00e+00, 5.00e+00, 3.60e+00, 1.40e+00, 2.00e-01],
       [5.00e+00, 5.40e+00, 3.90e+00, 1.70e+00, 4.00e-01],
       [6.00e+00, 4.60e+00, 3.40e+00, 1.40e+00, 3.00e-01],
       [7.00e+00, 5.00e+00, 3.40e+00, 1.50e+00, 2.00e-01],
       [8.00e+00, 4.40e+00, 2.90e+00, 1.40e+00, 2.00e-01],
       [9.00e+00, 4.90e+00, 3.10e+00, 1.50e+00, 1.00e-01],
       [1.00e+01, 5.40e+00, 3.70e+00, 1.50e+00, 2.00e-01],
       [1.10e+01, 4.80e+00, 3.40e+00, 1.60e+00, 2.00e-01],
       [1.20e+01, 4.80e+00, 3.00e+00, 1.40e+00, 1.00e-01],
       [1.30e+01, 4.30e+00, 3.00e+00, 1.10e+00, 1.00e-01],
       [1.40e+01, 5.80e+00, 4.00e+00, 1.20e+00, 2.00e-01],
       [1.50e+01, 5.70e+00, 4.40e+00, 1.50e+00, 4.00e-01],
       [1.60e+01, 5.40e+00, 3.90e+00, 1.30e+00, 4.00e-01

### Задача 5

Работайте с массивом, полученным при открытии **iris.csv**. Назовите его my_2d_array. Напиишите код, который считает сумму элементов массива по столбцам (для решения данной задачи воспользуйтесь разделом ноутбука "Операции с двумерными массивами и встроенные методы").

In [ ]:
my_2d_array=np.loadtxt('/content/iris.csv', delimiter=',', skiprows=1)
my_2d_array.sum(axis=0)


array([11175. ,   876.5,   458.6,   563.7,   179.9])

### Задача 6 

Используя библиотеку numpy, создайте массив формой 3x3 из случайных чисел от 11 до 41 не включительно (раздел "Семплирование из распределений"). 
* Выведите форму массива, убедитесь, что она совпадает с той, что вы задали.


В новой ячейке

* Не используя цикл for,  выведите на экран список элементов, которые строго меньше 20 (раздел "Индексация").

* Просуммируйте все элементы, не используя цикл (раздел "Встроенные методы").


In [ ]:
my_array=np.random.randint(11,41,(3,3))
print(my_array)
print(my_array.shape)

[[35 26 33]
 [13 18 36]
 [16 30 37]]
(3, 3)


In [ ]:
print(my_array[my_array<20])
my_array.sum()

[13 18 16]


244

### Задача 7

Создайте массив формой 5x5 из случайных целых от 1 до 11 не включительно.

* Выведите на экран элемент, находящийся в нулевой строке и нулевом столбце.

* Выведите на экран элемент, находящийся в первой строке и втором столбце.

* Выведите элементы третьей строки.

* Выведите элементы четвертого столбца.

В новой ячейке

* Выведите на экран элемент, который находится в четвертой строке и пятом столбце, посмотрите на информацию об ошибке (самая информативная строчка находится в самом конце **перед кнопкой search stack overflow**), переведите эту последнюю строчку на русский язык, постарайтесь запомнить ошибку и то, что ее вызвало


In [ ]:
my_array2=np.random.randint(1,11,(5,5))
print(my_array2)
print(my_array2[0,0])
print(my_array2[1,2])
print(my_array2[3,:])
print(my_array2[:,4])

[[6 6 9 1 6]
 [9 7 4 5 3]
 [2 8 1 8 4]
 [8 3 9 1 8]
 [9 2 2 4 3]]
6
4
[8 3 9 1 8]
[6 3 4 8 3]


In [ ]:
print(my_array2[4,5])

IndexError: ignored

## Pro версия

### Задача 1

* Подгрузите массив **iris.csv** и назовите его my_array. 

* Создайте двумерный массив из случайных чисел той же формы, что и my_array, не указывая его в ручную.(раздел "Семплирование из распределений", потребуется использовать размерность массива my_array).

* Назовите его my_generated_array.

In [ ]:
my_array=np.loadtxt('/content/iris.csv', delimiter=',',skiprows=1)
my_generated_array=np.random.random((my_array.shape))
print(my_generated_array)
print(my_array.shape)
print(my_generated_array.shape)


[[2.73477690e-01 4.17527279e-01 4.32947237e-01 5.42059563e-01
  1.03417193e-01]
 [5.98311179e-01 7.69799551e-01 5.20582658e-02 3.14424510e-01
  4.20653992e-01]
 [7.50540958e-01 5.45481090e-01 6.51730602e-01 5.59702478e-01
  3.56733001e-01]
 [3.46243777e-01 4.93792574e-02 5.25020039e-01 8.54858154e-01
  9.76975315e-02]
 [4.42068272e-01 3.50026208e-02 2.53904472e-01 2.74742490e-01
  1.81733179e-01]
 [4.00043615e-01 1.64416369e-01 7.44753479e-01 3.09835937e-01
  3.41924093e-02]
 [6.12528609e-01 1.54808657e-01 6.51781258e-02 9.69022373e-01
  5.11095641e-01]
 [8.33261287e-01 6.88616477e-01 1.22110224e-01 2.51280263e-01
  3.58134279e-01]
 [1.74864525e-01 4.92021868e-01 8.32852688e-01 5.69819469e-01
  9.43037993e-01]
 [2.72845734e-01 4.54608384e-01 6.94089639e-01 1.56610474e-01
  7.75576290e-01]
 [5.95772814e-01 3.32170678e-01 7.86567554e-01 3.51489838e-02
  3.47286895e-02]
 [9.28647961e-01 3.14915049e-01 5.48520389e-01 3.09793806e-01
  4.65793836e-01]
 [9.83644210e-02 7.48064614e-01 8.103521

### Задача 2

* Выполните поэлементное умножение my_array на my_generated_array (раздел "векторные операции").

* Склейте массивы my_array, my_generated_array в один (могут помочь методы np.concatenate, np.vstack, np.hstack).

* Возьмите склеенный массив и разделите его на равные части (больше двух). Можно сделать вручную через циклы либо воспользоваться методом vsplit.

In [ ]:
my_array*my_generated_array

array([[0.00000000e+00, 2.12938912e+00, 1.51531533e+00, 7.58883388e-01,
        2.06834386e-02],
       [5.98311179e-01, 3.77201780e+00, 1.56174798e-01, 4.40194314e-01,
        8.41307984e-02],
       [1.50108192e+00, 2.56376112e+00, 2.08553793e+00, 7.27613221e-01,
        7.13466003e-02],
       [1.03873133e+00, 2.27144584e-01, 1.62756212e+00, 1.28228723e+00,
        1.95395063e-02],
       [1.76827309e+00, 1.75013104e-01, 9.14056100e-01, 3.84639486e-01,
        3.63466358e-02],
       [2.00021808e+00, 8.87848395e-01, 2.90453857e+00, 5.26721092e-01,
        1.36769637e-02],
       [3.67517165e+00, 7.12119821e-01, 2.21605628e-01, 1.35663132e+00,
        1.53328692e-01],
       [5.83282901e+00, 3.44308238e+00, 4.15174762e-01, 3.76920394e-01,
        7.16268558e-02],
       [1.39891620e+00, 2.16489622e+00, 2.41527280e+00, 7.97747256e-01,
        1.88607599e-01],
       [2.45561161e+00, 2.22758108e+00, 2.15167788e+00, 2.34915712e-01,
        7.75576290e-02],
       [5.95772814e+00, 1.7937

In [ ]:
np.concatenate((my_array,my_generated_array))

array([[0.        , 5.1       , 3.5       , 1.4       , 0.2       ],
       [1.        , 4.9       , 3.        , 1.4       , 0.2       ],
       [2.        , 4.7       , 3.2       , 1.3       , 0.2       ],
       ...,
       [0.20281647, 0.397956  , 0.19291275, 0.97010434, 0.11427942],
       [0.91894644, 0.07440026, 0.64300097, 0.30051928, 0.95571735],
       [0.4447557 , 0.71385622, 0.32766031, 0.10997066, 0.8589235 ]])

In [ ]:
np.vstack((my_array,my_generated_array))

array([[0.        , 5.1       , 3.5       , 1.4       , 0.2       ],
       [1.        , 4.9       , 3.        , 1.4       , 0.2       ],
       [2.        , 4.7       , 3.2       , 1.3       , 0.2       ],
       ...,
       [0.20281647, 0.397956  , 0.19291275, 0.97010434, 0.11427942],
       [0.91894644, 0.07440026, 0.64300097, 0.30051928, 0.95571735],
       [0.4447557 , 0.71385622, 0.32766031, 0.10997066, 0.8589235 ]])

In [ ]:
np.hstack((my_array,my_generated_array))

array([[0.00000000e+00, 5.10000000e+00, 3.50000000e+00, ...,
        4.32947237e-01, 5.42059563e-01, 1.03417193e-01],
       [1.00000000e+00, 4.90000000e+00, 3.00000000e+00, ...,
        5.20582658e-02, 3.14424510e-01, 4.20653992e-01],
       [2.00000000e+00, 4.70000000e+00, 3.20000000e+00, ...,
        6.51730602e-01, 5.59702478e-01, 3.56733001e-01],
       ...,
       [1.47000000e+02, 6.50000000e+00, 3.00000000e+00, ...,
        1.92912750e-01, 9.70104341e-01, 1.14279417e-01],
       [1.48000000e+02, 6.20000000e+00, 3.40000000e+00, ...,
        6.43000974e-01, 3.00519279e-01, 9.55717354e-01],
       [1.49000000e+02, 5.90000000e+00, 3.00000000e+00, ...,
        3.27660311e-01, 1.09970665e-01, 8.58923497e-01]])

### Задача 3

Найдите все элементы массива my_array, которые больше трех и меньше 5 одновременно. Используйте методологию подвыборки массива с условием (раздел "Индексация").

In [ ]:
my_array[(my_array>3) & (my_array<5)]

array([3.5, 4.9, 4.7, 3.2, 4.6, 3.1, 4. , 3.6, 3.9, 4.6, 3.4, 3.4, 4.4,
       4.9, 3.1, 3.7, 4.8, 3.4, 4.8, 4.3, 4. , 4.4, 3.9, 3.5, 3.8, 3.8,
       3.4, 3.7, 4.6, 3.6, 3.3, 4.8, 3.4, 3.4, 3.5, 3.4, 4.7, 3.2, 4.8,
       3.1, 3.4, 4.1, 4.2, 4.9, 3.1, 3.2, 3.5, 4.9, 3.6, 4.4, 3.4, 3.5,
       4.5, 4.4, 3.2, 3.5, 3.8, 4.8, 3.8, 4.6, 3.2, 3.7, 3.3, 3.2, 4.7,
       3.2, 4.5, 3.1, 4.9, 4. , 4.6, 4.5, 3.3, 4.7, 4.9, 3.3, 4.6, 3.9,
       3.5, 4.2, 4. , 4.7, 3.6, 3.1, 4.4, 4.5, 4.1, 4.5, 3.9, 3.2, 4.8,
       4. , 4.9, 4.7, 4.3, 4.4, 4.8, 4.5, 3.5, 3.8, 3.7, 3.9, 4.5, 3.4,
       4.5, 3.1, 4.7, 4.4, 4.1, 4. , 4.4, 4.6, 4. , 3.3, 4.2, 4.2, 4.2,
       4.3, 4.1, 3.3, 4.9, 4.5, 3.6, 3.2, 3.2, 3.8, 3.2, 4.9, 4.9, 3.3,
       3.2, 4.8, 4.9, 3.8, 3.4, 3.1, 4.8, 3.1, 3.1, 3.1, 3.2, 3.3, 3.4])

### Задача 4
Создайте трехмерный массив формы 2х3х4, состоящий из случайных целых чисел от 15 до 37, не включительно.

Используя полученный массив, преобразуйте его в новый со следующими значениями:

    * "small", если значения меньше 20
    * "medium", если значения в промежутке [20, 30]
    * "large", если значения больше 30

На выходе должен быть массив той же формы, но состоящий из строк.

Подсказка - создайте массив из строк, и меняйте его, опираясь на массив из чисел.

In [ ]:
my_array3=np.random.randint(15,37,(2,3,4))
my_array3_changed=np.zeros_like(my_array3, 'U8')
my_array3_changed[my_array3<20]='small'
my_array3_changed[(my_array3>=20)& (my_array3<=30)]='medium'
my_array3_changed[my_array3>30]='large'
print(my_array3)
print('\n',my_array3_changed)

[[[23 30 30 26]
  [17 35 24 34]
  [32 33 28 24]]

 [[31 21 19 32]
  [17 23 32 18]
  [15 16 18 32]]]

 [[['medium' 'medium' 'medium' 'medium']
  ['small' 'large' 'medium' 'large']
  ['large' 'large' 'medium' 'medium']]

 [['large' 'medium' 'small' 'large']
  ['small' 'medium' 'large' 'small']
  ['small' 'small' 'small' 'large']]]


### Задача 5

Создайте одномерный массив из случайных 10 вещественных значений. Выведите массив на экран.

* Не используя циклы, найдите сумму значений с 3 по 7 элемент, не включительно. Помните, что индексы начинаются с 0.
* Найдите сумму квадратов последних двух элементов. 

Продвинутый вариант решения - взять два последних значения подвыборкой, применив отрицательную индексацию и слайсинг, возведя выбранный массив в квадрат и просуммировав значения.

In [ ]:
my_array4 = np.random.uniform(10,size=10)
print(my_array4)
print(my_array4[2:6].sum())
print((my_array4[-2:]**2).sum())


[8.85020279 7.87936096 8.82848155 5.2259237  6.05608507 3.21834113
 7.1742951  3.84400064 2.91388421 2.49431024]
23.328831445570476
14.712304766978821


### Задача 6

* Создайте структурированный массив (гуглите structured arrays numpy), который будет содержать списки с именем студента(str), его возрастом(int) и средней оценкой(float) (обратите внимание на пример с занятия со списком автомобильных регионов).
* Отсортируйте такой массив по одной из колонок.(обратите внимание на параметр order метода sort()).
* Замените значение, отвечающее за возраст, у всех студентов на одно и то же, например, 10.

In [ ]:
my_array5=np.array([('Sergey', 19, 4.85),('Roman', 18, 4.43),('Egor', 20, 4.65),('Elena', 20, 4.70)], dtype=[('Name', 'U16'),('Age', int),('Average grade', float)])
my_array5


array([('Sergey', 19, 4.85), ('Roman', 18, 4.43), ('Egor', 20, 4.65),
       ('Elena', 20, 4.7 )],
      dtype=[('Name', '<U16'), ('Age', '<i8'), ('Average grade', '<f8')])

In [ ]:
my_array5.sort(order='Average grade')
print(my_array5)

[('Roman', 18, 4.43) ('Egor', 20, 4.65) ('Elena', 20, 4.7 )
 ('Sergey', 19, 4.85)]


In [ ]:
my_array5['Age']=10
print(my_array5)

[('Roman', 10, 4.43) ('Egor', 10, 4.65) ('Elena', 10, 4.7 )
 ('Sergey', 10, 4.85)]


### Задача 7

Создайте массив формы 5х5 из случайных целых чисел (промежуток на ваше усмотрение).

* Выведите массив на экран

В новой ячейке:

* Получите на вход с помощью input два числа - координаты элемента в массиве (номер строки и номер столбца)

* Выведите все 8 соседних элементов в любом формате.

Подсказка: 


```
* * * *
* х х х
* х о х
* х х х
```

в примере выше для элемента "о" элементы "х" являются соседними

* проведите серию экспериментов (указывайте разные координаты)
обратите внимание, при каких значениях будет вылетать ошибка


In [ ]:
import numpy as np
my_array7=np.arange(1,26).reshape(5,5)
my_array7


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
my_array7[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [ ]:
a=int(input('Введите координату 1: '))
b=int(input('Введите координату 2: '))
print(my_array7[a,b])
my_array7[a-1:a+2,b-1:b+2]

Введите координату 1: 0
Введите координату 2: 1
2


array([], shape=(0, 3), dtype=int64)